apiVersion: apps/v1
kind: Deployment
metadata:
  name: engeo-frontend-deployment
  namespace: "2401018"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engeo-connect
  template:
    metadata:
      labels:
        app: engeo-connect
    spec:
      containers:
        - name: engeo-connect
          image: vaibhavi/ngo:v1   # Docker Hub image or your local image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80