apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engeo-ingress
  namespace: "2401018"
spec:
  ingressClassName: nginx
  rules:
    - host: 2401018.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: engeo-frontend-service
                port:
                  number: 80