apiVersion: v1
kind: Service
metadata:
  name: engeo-frontend-service
  namespace: "2401018"
spec:
  type: NodePort
  selector:
    app: engeo-connect
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 31075